package com.happylittleapps.osrs.general;

import org.osbot.rs07.api.map.Position;

public class Location {
	
	public static final Location GOBLIN_VILLAGE = new Location("Goblin Village", new Position(2956, 3501, 0));
	public static final Location GNOME_BALL_FIELD = new Location("Gnome Ball Field", new Position(2381, 3484, 0));
	public static final Location GRAND_TREE = new Location("Grand Tree", new Position(2465, 3490, 0));
	public static final Location GNOME_AGILITY_ARENA = new Location("Gnome Agility Training Arena", new Position(2470, 3435, 0));
	public static final Location FISHING_COLONY = new Location("Piscatoris Fishing Colony", new Position(2332, 3656, 0));
	public static final Location FALCONER = new Location("Falconer", new Position(2371, 3623, 0));
	public static final Location EAGLES_PEAK = new Location("Eagles' Peak", new Position(2365, 3457, 0));
	public static final Location TREE_GNOME_STRONGHOLD = new Location("Tree Gnome Stronghold", new Position(2458, 3421, 0));
	public static final Location CASTLE_WARS = new Location("Castle Wars", new Position(2440, 3089, 0));
	public static final Location JIGGIG = new Location("Jiggig", new Position(2448, 3050, 0));
	public static final Location OBSERVATORY = new Location("Observatory", new Position(2448, 3174, 0));
	public static final Location TREE_GNOME_VILLATE = new Location("Tree Gnome Village", new Position(2503, 3191, 0));
	public static final Location BARBARIAN_ASSAULT = new Location("Barbarian Assault", new Position(2533, 3569, 0));
	public static final Location BARBARIAN_OUTPOST = new Location("Barbarian Outpost", new Position(2542, 3564, 0));
	public static final Location BARBARIAN_AGILITY_TRAINING_AREA = new Location("Barbarian Agility Training Area", new Position(2542, 3564, 0));
	public static final Location OTTOS_GROTTO = new Location("Otto's Grotto", new Position(2506, 3488, 0));
	public static final Location COMBAT_TRAINING_CAMP = new Location("Combat Training Camp", new Position(2518, 3354, 0));
	public static final Location WEST_ARDOUGNE = new Location("West Ardougne", new Position(2561, 3299, 0));
	public static final Location EAST_ARDOUGNE = new Location("East Ardougne", new Position(2632, 3298, 0));
	public static final Location BATTLEFIELD = new Location("Battlefield", new Position(2521, 3236, 0));
	public static final Location MONASTRY = new Location("Monastry", new Position(2605, 3219, 0));
	public static final Location CLOCKTOWER = new Location("Clocktower", new Position(2564, 3236, 0));
	public static final Location TOWER_OF_LIFE = new Location("Tower of Life", new Position(2648, 3227, 0));
	public static final Location NECROMANCER = new Location("Necromancer", new Position(2663, 3241, 0));
	public static final Location FIGHT_ARENA = new Location("Fight Arena", new Position(2577, 3155, 0));
	public static final Location NIGHTMARE_ZONE = new Location("Nightmare Zone", new Position(2609, 3114, 0));
	public static final Location WIZARDS_GUILD = new Location("Wizards Guild", new Position(2599, 3087, 0));
	public static final Location YANILLE = new Location("Yanille", new Position(2571, 3089, 0));
	public static final Location PORT_KHAZARD = new Location("Port Khazard", new Position(2644, 3159, 0));
	public static final Location GUTANOTH = new Location("Gu'Tanoth", new Position(2558, 3052, 0));
	public static final Location FISHING_GUILD = new Location("Fishing Guild", new Position(2610, 3392, 0));
	public static final Location HEMENSTER = new Location("Hemenster", new Position(2645, 3440, 0));
	public static final Location WITCHAVEN = new Location("Witchaven", new Position(2720, 3289, 0));
	public static final Location LEGENDS_GUILD = new Location("Legends' Guild", new Position(2729, 3347, 0));
	public static final Location SORCERERS_TOWER = new Location("Sorcerer's Tower", new Position(2702, 3393, 0));
	public static final Location RANGING_GUILD = new Location("Ranging Guild", new Position(2657, 3440, 0));
	public static final Location KEEP_LE_FAYE = new Location("Keep Le Faye", new Position(2758, 3401, 0));
	public static final Location MCGRUBORS_WOOD = new Location("McGrubor's Wood", new Position(2650, 3467, 0));
	public static final Location COAl_TRUCKS = new Location("Coal Trucks", new Position(2602, 3490, 0));
	public static final Location SEERS_VILLAGE = new Location("Seers' Village", new Position(2705, 3483, 0));
	public static final Location CAMELOT_CASTLE = new Location("Camelot Castle", new Position(2757, 3480, 0));
	public static final Location FLAX = new Location("Flax", new Position(2741, 3443, 0));
	public static final Location SINCLAIR_MANSION = new Location("Sinclair Mansion", new Position(2742, 3552, 0));
	public static final Location RELLEKA = new Location("Relleka", new Position(2658, 3659, 0));
	public static final Location ROCK_CRABS_WEST = new Location("Rock Crabs West", new Position(2677, 3716, 0));
	public static final Location ROCK_CRABS_EAST = new Location("Rock Crabs East", new Position(2700, 3723, 0));
	public static final Location KELDAGRIM_ENTRANCE = new Location("Keldagrim Entrance", new Position(2725, 3713, 0));
	public static final Location GOLDEN_APPLE_TREE = new Location("Golden Apple Tree", new Position(2757, 3607, 0));
	public static final Location MOUNTAIN_CAMP = new Location("Mountain Camp", new Position(2755, 3650, 0));
	public static final Location TROLLWEISS_MOUNTAIN = new Location("Trollweiss Mountain", new Position(2783, 3847, 0));
	public static final Location CATHERBY = new Location("Catherby", new Position(2819, 3446, 0));
	public static final Location TAVERLY = new Location("Taverley", new Position(2897, 3455, 0));
	public static final Location HEROES_GUILD = new Location("Heroes' Guild", new Position(2904, 3510, 0));
	public static final Location BURTHORPE = new Location("Burthorpe", new Position(2898, 3545, 0));
	public static final Location CHAOS_TEMPLE = new Location("Chaos Temple", new Position(2942, 3517, 0));
	public static final Location WARRIORS_GUILD = new Location("Warriors' Guild", new Position(2879, 3546, 0));
	public static final Location FALADOR = new Location("Falador", new Position(2965, 3379, 0));
	public static final Location DARK_WIZARDS_TOWER = new Location("Dark Wizards' Tower", new Position(2915, 3334, 0));
	public static final Location CRAFTING_GUILD = new Location("Crafting Guild", new Position(2933, 3292, 0));
	public static final Location MELZARS_MAZE = new Location("Melzar's Maze", new Position(2943, 3247, 0));
	public static final Location RIMMINGTON = new Location("Rimmington", new Position(2957, 3215, 0));
	public static final Location PORT_SARIM = new Location("Port Sarim", new Position(3019, 3245, 0));
	public static final Location MUDSKIPPER_POINT = new Location("Mudskipper Point", new Position(2997, 3121, 0));
	public static final Location DWARVEN_MINE = new Location("Dwarven Mine", new Position(3015, 3449, 0));
	public static final Location MONASTERY = new Location("Monastery", new Position(3051, 3493, 0));
	public static final Location BARBARIAN_VILLAGE = new Location("Barbarian Village", new Position(3077, 3420, 0));
	public static final Location BLACK_KNIGHTS_FORTRESS = new Location("Black Knights' Fortress", new Position(3005, 3517, 0));
	public static final Location ICE_MOUNTAIN = new Location("Ice Mountain", new Position(3032, 3471, 0));
	public static final Location DRAYNOR_VILLAGE = new Location("Draynor Village", new Position(3092, 3248, 0));
	public static final Location WIZARDS_TOWER = new Location("Wizards' Tower", new Position(3109, 3169, 0));
	public static final Location DRAYNOR_MANOR = new Location("Draynor Manor", new Position(3108, 3351, 0));
	public static final Location EDGEVILLE = new Location("Edgeville", new Position(3088, 3490, 0));
	public static final Location GRAND_EXCHANGE = new Location("Grand Exchange", new Position(3164, 3483, 0));
	public static final Location COOKS_GUILD = new Location("Cooks' Guild", new Position(3142, 3441, 0));
	public static final Location LUMBRIDGE = new Location("Lumbridge", new Position(3234, 3218, 0));
	public static final Location LUMBRIDGE_SWAMP = new Location("Lumbridge Swamp", new Position(3199, 3178, 0));
	public static final Location CHAMPIONS_GUILD = new Location("Champions' Guild", new Position(3191, 3365, 0));
	public static final Location VARROCK = new Location("Varrock", new Position(3211, 3424, 0));
	public static final Location VARROCK_WEST_BANK = new Location("Varrock West Bank", new Position(3182, 3439, 0));
	public static final Location VARROCK_EAST_BANK = new Location("Varrock East Bank", new Position(3253, 3420, 0));
	public static final Location LUMBER_YARD = new Location("Lumber Yard", new Position(3308, 3494, 0));
	public static final Location DUEL_ARENA = new Location("Duel Arena", new Position(3366, 3267, 0));
	public static final Location DUEL_ARENA_ENTRANCE = new Location("Duel Arena Entrance", new Position(3315, 3234, 0));
	public static final Location AL_KHARID = new Location("Al Kharid", new Position(3293, 3185, 0));
	public static final Location MAGE_TRAINING_ARENA = new Location("Mage Training Arena", new Position(3363, 3292, 0));
	public static final Location CLAN_WARS = new Location("Clan Wars", new Position(3368, 3167, 0));
	public static final Location SHANTAY_PASS = new Location("Shantay Pass", new Position(3303, 3122, 0));
	public static final Location MUSA_POINT = new Location("Musa Point", new Position(2912, 3150, 0));
	public static final Location BRIMHAVEN = new Location("Brimhaven", new Position(2773, 3185, 0));
	public static final Location SHIP_YARD = new Location("Ship Yard", new Position(2973, 3043, 0));
	public static final Location TAI_BWO_WANNAI = new Location("Tai Bwo Wannai", new Position(2790, 3064, 0));
	public static final Location SHILO_VILLAGE = new Location("Shilo Village", new Position(2852, 2953, 0));
	public static final Location CAIRN_ISLE = new Location("Cairn Isle", new Position(2768, 2977, 0));
	public static final Location CANAFIS = new Location("Canafis", new Position(3493, 3490, 0));
	public static final Location SLAYER_TOWER = new Location("Slayer Tower", new Position(3428, 3528, 0));
	public static final Location MAUSOLEUM = new Location("Mausoleum", new Position(3503, 3571, 0));
	public static final Location FENKENSTRAINS_CASTLE = new Location("Fenkenstrain's Castle", new Position(3549, 3533, 0));
	public static final Location ECTOFUNTUS = new Location("Ectofuntus", new Position(3659, 3525, 0));
	public static final Location PORT_PHASMATYS = new Location("Port Phasmatys", new Position(3673, 3486, 0));
	public static final Location CASTLE_DRAKAN = new Location("Castle Drakan", new Position(3565, 3358, 0));
	public static final Location BARROWS = new Location("Barrows", new Position(3565, 3313, 0));
	public static final Location MORTTON = new Location("Mort'ton", new Position(3487, 3283, 0));
	public static final Location BURGH_DE_ROTT = new Location("Burgh de Rott", new Position(3502, 3218, 0));
	public static final Location ABANDONED_MINE = new Location("Abandoned Mine", new Position(3444, 3252, 0));
	public static final Location THE_HOLLOWS = new Location("The Hollows", new Position(3497, 3381, 0));
	public static final Location MEIYERDITCH = new Location("Meiyerditch", new Position(3608, 3285, 0));
	public static final Location DIGSITE = new Location("Digsite", new Position(3361, 3388, 0));
	public static final Location EXAM_CENTER = new Location("Exam Centre", new Position(3352, 3341, 0));
	
	String Name;
	Position Position;

	public Location(String name, Position pos) {
		Name = name;
		Position = pos;
	}
}